logging:
    level:
#        org.springframework.security: DEBUG
#    pattern:
#        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: /var/log/spring/microservices/adgs-zuul-server.log
